### ISSUE TITLE
Front panel disappeared

### ISSUE THREAD

**Issue by mjohanning99** [NsCDE/NsCDE#29] opened 2020-08-26 20:26 UTC
Hey there,

I hate having to open another issue here, but, somehow, the front panel has disappeared. I was simply changing the theme in the Style Manager to something different when, suddenly, the front panel simply disappeared. Reverting the theme didn't help, neither did restarting and attempting to use the several methods of toggling the front panel (such as Shift+Esc). 
Any ideas what might've caused this?

**Comment by NsCDE** [comment] 2020-08-26 23:24
Hi,
Try this three things:

1. If $HOME/.NsCDE/FrontPanel.actions exists, move it outside of .NsCDE folder temporary and Restart NsCDE/FVWM.

2. If this is not the cause, attach your $HOME/.xsession-errors here, so we can examine X diagnostic output.

3. Make sure you don't have "InfoStoreAdd sandboxmode" set to 1 in $HOME/.NsCDE/NsCDE.conf

**Comment by mjohanning99** [comment] 2020-08-27 17:35
Hey,

thanks for your response! I have deleted the `FrontPanel.actions` and the `SubPanel.actions` files and after restarting NsCDE, the front panel has reappeared. I then put the `SubPanels.actions` back in, restarted and it stopped working again; so I believe it has to do with my `SubPanel.actions` file.

**Comment by mjohanning99** [comment] 2020-08-27 17:37
Sorry, I appear to have hit the wrong button! I only added a couple of programs to one of the subpanels and it was working fine until I updated the colourscheme. Here is a copy of the file: 
```
S2,WIDTH,160
S2,ENABLED,1
S7,NAME,$[gt.Desktop Settings]
S7,WIDTH,196
S7,ENABLED,1
S7,ENTRY,$[gt.Style Manager],FVWM-F,NsCDE/Fpstyle.m.xpm,f_ToggleFvwmModule FvwmScript StyleMgr
S7,ENTRY,Atril Document Viewer,,32x32-atril.png, atril
S7,ENTRY,$[gt.Workspaces and Pages],FVWM-F,NsCDE/32x32/apps/system-workspaces-pages-manager.png,f_ToggleFvwmModule FvwmScript WsPgMgr $[infostore.desknum] $[infostore.pagematrixX] $[infostore.pagematrixY]
S7,ENTRY,$[gt.Qt4 Config],,hicolor/32x32/apps/qt4-logo.png,qtconfig-qt4
S7,ENTRY,$[gt.Qt5 Settings],,NsCDE/32x32/apps/preferences-desktop-theme.png,qt5ct
S7,ENTRY,$[gt.Dconf Editor],,hicolor/32x32/apps/ca.desrt.dconf-editor.png,dconf-editor
S7,ENTRY,$[gt.NsCDE Log],FVWM-F,CDE/SDtErrors.m.pm,f_ToggleExecWindow WatchWinMgrErrors UrgencyFunc xterm -title \\\\\\"Watch Errors\\\\\\" -name WatchWinMgrErrors -e $[infostore.xlogcmd]
S8,NAME,$[gt.Tools]
S8,WIDTH,160
S8,ENTRY,Atom,,32x32-atom.png,atom
S8,ENTRY,FileZilla,,hicolor/32x32/apps/filezilla.png,filezilla
```

**Comment by mjohanning99** [comment] 2020-08-27 20:02
I have been trying out some stuff and found out that I am able to add new icons to the submenu using the `Install Icon` functionality. They then appear within that submenu and are executable. When I _then_, however, restart NsCDE, the Front Panel simply disappears and it can only mitigated by deleting the `NsCDE-Subpanels.conf` file (not, as I had previously thought, the `Subpanels.actions` file). Thus, here is a copy of the file that breaks the Front Panel: [NsCDE-Subpanels.conf.txt](https://github.com/NsCDE/NsCDE/files/5138536/NsCDE-Subpanels.conf.txt)

**Comment by NsCDE** [comment] 2020-08-28 01:36
Hi Marvin,

Subpanels.actions is the source, while NsCDE-Subpanels.conf is generated from it.

In your Subpanels.actions, S8 lines are missing line `S8,ENABLED,1`. This is why non-working configuration is generated. Put that line someware where "S8" lines are, remove $FVWM_USERDIR/NsCDE-Subpanels.conf, restart NsCDE, and then open any subpanel, click on the left and only titlebar button, and from popdown menu choose "Refresh Subpanel" - this will trigger (re)generation of the NsCDE-Subpanels.conf.

From my side, I will see how to make this less error prone, but **important question** for me is: did you edited Subpanels.actions manually with editor at any point, or it appeared without "S8,ENABLED,1" line just like that? In the former case, I can only harden things to be less error prone, but in later case, there is a potential bug here, and I have to find a way how to trigger it.

**Comment by mjohanning99** [comment] 2020-08-28 07:29
Hey,

thank you for your response. I honestly don't remember ever having edited the `Subpanels.actions` on my own, but I'm not entirely sure; especially since I am unable to reproduce the error after having deleted it. My guess is that I probably accidentally deleted the `S8,ENABLED,1` line whilst inspecting the file, since I am unsure what else it could've been.

**Comment by NsCDE** [comment] 2020-08-28 14:01
Ok, I have hardened generate_subpanels helper script in pending_release branch, so if this happens someware, that subpanel will be disabled and Front Panel started anyway.
All in all, no matter if you edited by hand, generate_subpanels needed some hardening.
Closing this for now.

**Closed by NsCDE** 2020-08-28 14:01 UTC
