### ISSUE TITLE
Why does it look terrible?

### ISSUE THREAD

**Issue by UnBeatWaterGH** [NsCDE/NsCDE#143] opened 2023-02-28 21:55 UTC
The font is wrong and looks wrong, turn of anti-aliasing or enable anti-aliasing for everything else (like icons and really just everything).

**Comment by UnBeatWaterGH** [comment] 2023-02-28 21:56
Also the - button on those windows looks horrible

**Comment by UnBeatWaterGH** [comment] 2023-02-28 21:58
For now I will stick to original CDE (which has a Linux port)

**Comment by UnBeatWaterGH** [comment] 2023-02-28 22:01
Actually everything in your project looks terrible when I really look at it! Congrats on ruining my love for CDE 🎉!

**Comment by tim78245** [comment] 2023-03-03 04:20
Could you post some screenshots as a comparison between the good looking CDE and the ugly NsCDE?

**Comment by UnBeatWaterGH** [comment] 2023-03-03 05:11
Haven’t installed NsCDE because of bad look (screenshot on NsCDE main page). Screenshot of good CDE (aka CDE) found on Wikipedia page for CDE.

**Comment by tim78245** [comment] 2023-03-03 06:20
So:
- the menu button is too thick (I actually prefer NsCDE's)
Check out:
https://www.fvwm.org/Wiki/Config/VectorButtons/
https://www.fvwm.org/Wiki/Decor/CDE/
- The font is wrong (I wouldn't know, I changed it and I use Unifont for the titlebars because FVWM2 doesn't support fallback fonts).

You said "actually everything", can you provide more specific issues with NsCDE?

**Comment by UnBeatWaterGH** [comment] 2023-03-04 22:43
I do use CDE! I have compiled and used many many times. But while I was looking for a prebuilt CDE package for FreeBSD I came across this project.

**Comment by UnBeatWaterGH** [comment] 2023-03-04 22:45
> You said "actually everything", can you provide more specific issues with NsCDE?

The borders around different UI controls look like the top and side have different stroke widths. In Motif/CDE it is always 1px.

**Comment by UnBeatWaterGH** [comment] 2023-03-05 18:35
> I think you are not using either CDE or NsCDE. You are just a troll.
Can't you see that I'm looking at your project's screenshots and noticing ugly differences, and as a humble man I wanted to tell you (Example: you know, the whole border thing above) and you tell me that you don't want any help with accuracy? Your project might be the thing to morph the Motif/CDE look with differences, what I'm trying to say here is a future scenario where CDE is completely forgotten, with NsCDE taking it's place, and without my contributions, CDE (as humanity would know it) would be different looking than the true CDE.

**Comment by tim78245** [comment] 2023-03-06 06:57
> The borders around different UI controls (mainly pop ups and windows) look like the top and side have different stroke widths. In Motif/CDE it is always 1px.

I think I know what you're talking about?
In KMag:
![image](https://user-images.githubusercontent.com/111637211/223037578-167b6f81-65b2-4652-8fe2-834e4961da1c.png)
The bluebox has a 2 pixel border, and the brown button has a one pixel border. Am I right?

> you don't want any help with accuracy?

More nitpicking is useful, screenshots make it easier as describing UI elements can be difficult. Yes those useless red circles on youtube videos, or zooming in on an element, would be useful here :)

**Comment by Minda1975** [comment] 2023-03-06 12:11
> Can't you see that I'm looking at your project's screenshots and noticing ugly differences? And as a humble man I wanted to tell you about it (Example: you know, the whole border thing above) and you tell me that you don't want any help with accuracy? Your project might be the thing to morph the Motif/CDE look with differences, what I'm trying to say here is a future scenario where CDE is completely forgotten, with NsCDE taking it's place, and without my contributions, CDE (as humanity would know it) would be different looking than the true CDE.

Ok, now I understand what you mean. But the problem is that I am not the author of this project. I have tried this project before and I can tell you that it is not perfect. There really isn't. In addition, it uses more computer resources than a system with CDE.

**Comment by UnBeatWaterGH** [comment] 2023-03-07 03:14
I don’t care that you aren’t the creator, sometimes to say certain things you have to say “you” instead of “you guys” or something like that.

**Comment by UnBeatWaterGH** [comment] 2023-03-07 03:16
> > The borders around different UI controls (mainly pop ups and windows) look like the top and side have different stroke widths. In Motif/CDE it is always 1px.
> 
> I think I know what you're talking about? In KMag: ![image](https://user-images.githubusercontent.com/111637211/223037578-167b6f81-65b2-4652-8fe2-834e4961da1c.png) The bluebox has a 2 pixel border, and the brown button has a one pixel border. Am I right?
> 
> > you don't want any help with accuracy?
> 
> More nitpicking is useful, screenshots make it easier as describing UI elements can be difficult. Yes those useless red circles on youtube videos, or zooming in on an element, would be useful here :)

Not exactly. Open a pop up from the toolbar and the border may have a width of 1px with a height of 2. Which doesn’t look right, but you actually brought up another problem that I wasn’t able to see from looking at the screenshots! Good for you!

**Comment by tim78245** [comment] 2023-03-07 05:07
> Not exactly. Open a pop up from the toolbar and the border may have a width of 1px with a height of 2. Which doesn’t look right, but you actually brought up another problem that I wasn’t able to see from looking at the screenshots! Good for you!
> 
> Note: When referring to “Toolbar” I’m talking about the movable bar that by default is at the bottom of your screen.

Ah ok, what is here labelled Subpanel name and subpanel menu button:
https://github.com/NsCDE/NsCDE/blob/master/doc/docbook/img/fig_subpanels.png

It seems to me you're half right. The top and side borders do not match, the top is 2px and the side is 1px. Half right, because based on screenshots I'm finding, both are supposed to be 2px, not 1px as you said previously:
http://toastytech.com/guis/solcdegeneral.png
http://www.xwinman.org/screenshots/cde-edward.png
https://docs.oracle.com/cd/E19455-01/806-1360/images/fpcopymain.epsi.gif

I'm not sure where to make the edit to fix that.

**Comment by UnBeatWaterGH** [comment] 2023-03-09 15:20
> both are supposed to be 2px, not 1px as you said previously:

Everyone makes mistakes when they're on a phone and looking at only one screenshot.

**Comment by NsCDE** [comment] 2023-04-29 18:25
> It seems to me you're half right. The top and side borders do not match, the top is 2px and the side is 1px. Half right, because based on screenshots I'm finding, both are supposed to be 2px, not 1px as you said previously: http://toastytech.com/guis/solcdegeneral.png http://www.xwinman.org/screenshots/cde-edward.png https://docs.oracle.com/cd/E19455-01/806-1360/images/fpcopymain.epsi.gif
> 
> I'm not sure where to make the edit to fix that.

Yup, that's a bug in Kvantum based Qt5 theme, I was basing this on Commonality work of Phob1an, and had a month of work to make everything dynamic for CDE color schemes, but that one has left unnoticed for a time. It will be fixed for 2.3 hopefully.

**Closed by NsCDE** 2023-04-29 18:25 UTC
