### ISSUE TITLE
High CPU / lockup when switching workspaces

### ISSUE THREAD

**Issue by no3m** [NsCDE/NsCDE#100] opened 2022-02-20 02:50 UTC
When switching workspaces, there are numerous ImageMagik 'convert' and 'fvwm-root' processes spawned to render the background(s).  Sometimes this creates significant CPU load and the window manager (and applications in general) temporarily becomes unresponsive.  Most noticeable in multi-head configurations
![ScreenShot 'Alacritty' 0x2400002 20220219 214039](https://user-images.githubusercontent.com/5472512/154826543-a65c16b4-fe3d-4d5d-82e8-0e0175daee58.png)
.

**Comment by NsCDE** [comment] 2022-02-20 07:03
Weird!

This processes shoud exit immediately. It looks like something hangs them. I tried, but I cannot reproduce this.

What OS/distro? What version of ImageMagick?

Please check if your partition is not full or something like that.

Also, try to list full process cmdline of fvwm-root (ps auxwww) and try to repeat that from the command line. I'm surprised to see multiple fvwm-root processes. When fvwm-root displays the image, it should exit immediately. ImageMagic's convert too.

Last, logout, kill this processes and log in again, maybe fvwm itself was hanging together with all child processes.

**Comment by no3m** [comment] 2022-02-20 17:35
Arch Linux, latest updates.  Four monitors, xrandr cmd in .xinitrc:

xrandr --output DVI-0 --primary --mode 1920x1080 --pos 1920x1080 --rotate normal --output DVI-1 --mode 1920x1080 --pos 3840x1080 --rotate normal --output DVI-1-2 --mode 1920x1080 --pos 0x0 --rotate normal --output DVI-1-3 --mode 1920x1080 --pos 0x1080 --rotate normal

convert --version
Version: ImageMagick 7.1.0-25 Q16-HDRI x86_64 2022-02-16 https://imagemagick.org
Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5)
Delegates (built-in): bzlib cairo djvu fontconfig freetype heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff webp wmf x xml zip zlib
Compiler: gcc (11.2)

Plenty disk space:
/dev/sda3       928G  282G  646G  31% /


$ time fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/0/TILED_NULL+DVI-1_1920_1080_3840_1080/1/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk1-Noise.pm+Desk2-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png

real	0m1.315s
user	0m0.753s
sys	0m0.100s


Seems multiple 'convert' processes are sometimes spawned even when only performing a single workspace switch action.  Sometimes none at all, just 'fvwm-root'.

Captured process list after switching workspaces a few times, processes piling on until system load very high and system responsiveness suffers:

`eric        2915 34.7  2.7 521300 453220 tty1    Rl   12:18   0:04 convert ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk3-Noise.pm -repage +1920+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk1-Noise.pm -repage +3840+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk2-Noise.pm -repage +0+0 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk4-Noise.pm -repage +0+1080 ) -layers merge /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/2/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/1/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk3-Noise.pm+Desk1-Noise.pm+Desk2-Noise.pm+Desk4-Noise.pm.png

eric        2941 34.2  2.7 586244 452928 tty1    Rl   12:18   0:04 convert ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk3-Noise.pm -repage +1920+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk1-Noise.pm -repage +3840+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk2-Noise.pm -repage +0+0 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk4-Noise.pm -repage +0+1080 ) -layers merge /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/2/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/1/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk3-Noise.pm+Desk1-Noise.pm+Desk2-Noise.pm+Desk4-Noise.pm.png

eric        2943 35.3  2.7 586248 453028 tty1    Rl   12:18   0:04 convert ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk3-Noise.pm -repage +1920+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk1-Noise.pm -repage +3840+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk2-Noise.pm -repage +0+0 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk4-Noise.pm -repage +0+1080 ) -layers merge /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/2/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/1/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk3-Noise.pm+Desk1-Noise.pm+Desk2-Noise.pm+Desk4-Noise.pm.png

eric        2944 34.9  2.7 586244 452896 tty1    Rl   12:18   0:04 convert ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk3-Noise.pm -repage +1920+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk1-Noise.pm -repage +3840+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk2-Noise.pm -repage +0+0 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk4-Noise.pm -repage +0+1080 ) -layers merge /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/2/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/1/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk3-Noise.pm+Desk1-Noise.pm+Desk2-Noise.pm+Desk4-Noise.pm.png

eric        2973 35.1  2.7 521296 453460 tty1    Rl   12:18   0:04 convert ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk3-Noise.pm -repage +1920+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk1-Noise.pm -repage +3840+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk2-Noise.pm -repage +0+0 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk4-Noise.pm -repage +0+1080 ) -layers merge /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/2/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/1/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk3-Noise.pm+Desk1-Noise.pm+Desk2-Noise.pm+Desk4-Noise.pm.png

eric        2974 34.7  2.7 586248 453116 tty1    Rl   12:18   0:04 convert ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk3-Noise.pm -repage +1920+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk1-Noise.pm -repage +3840+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk2-Noise.pm -repage +0+0 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk4-Noise.pm -repage +0+1080 ) -layers merge /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/2/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/1/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk3-Noise.pm+Desk1-Noise.pm+Desk2-Noise.pm+Desk4-Noise.pm.png

eric        2994 35.1  2.7 586248 452900 tty1    Rl   12:18   0:04 convert ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk3-Noise.pm -repage +1920+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk1-Noise.pm -repage +3840+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk2-Noise.pm -repage +0+0 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk4-Noise.pm -repage +0+1080 ) -layers merge /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/2/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/1/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk3-Noise.pm+Desk1-Noise.pm+Desk2-Noise.pm+Desk4-Noise.pm.png

eric        3000 36.0  2.7 586244 453096 tty1    Rl   12:18   0:04 convert ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk3-Noise.pm -repage +1920+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk1-Noise.pm -repage +3840+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk2-Noise.pm -repage +0+0 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk4-Noise.pm -repage +0+1080 ) -layers merge /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/2/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/1/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk3-Noise.pm+Desk1-Noise.pm+Desk2-Noise.pm+Desk4-Noise.pm.png

eric        3007 37.0  2.7 586244 452892 tty1    Rl   12:18   0:04 convert ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk3-Noise.pm -repage +1920+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk1-Noise.pm -repage +3840+1080 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk2-Noise.pm -repage +0+0 ) ( -size 1920x1080 tile:/home/eric/.NsCDE/backer/Desk4-Noise.pm -repage +0+1080 ) -layers merge /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/2/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/1/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk3-Noise.pm+Desk1-Noise.pm+Desk2-Noise.pm+Desk4-Noise.pm.png

eric        3029  8.7  0.0  62424 11772 tty1     S    12:18   0:00 fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/1/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk2-Noise.pm+Desk1-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png

eric        3030  8.5  0.0  62424 11740 tty1     S    12:18   0:00 fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/1/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk2-Noise.pm+Desk1-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png

eric        3031  9.5  0.0  62424 11836 tty1     S    12:18   0:00 fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/1/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk2-Noise.pm+Desk1-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png

eric        3042 12.0  0.0  62424 11872 tty1     S    12:18   0:00 fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/1/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk2-Noise.pm+Desk1-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png

eric        3043 11.8  0.0  62424 11672 tty1     S    12:18   0:00 fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/1/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk2-Noise.pm+Desk1-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png

eric        3044 11.7  0.0  62424 11732 tty1     S    12:18   0:00 fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/1/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk2-Noise.pm+Desk1-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png

eric        3055  7.0  0.3 161148 60372 tty1     S    12:18   0:00 fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/1/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk2-Noise.pm+Desk1-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png

eric        3056  0.2  0.0  62308 11264 tty1     S    12:18   0:00 fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/1/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk2-Noise.pm+Desk1-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png

eric        3057  0.2  0.0  62308 11348 tty1     S    12:18   0:00 fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/1/TILED_NULL+DVI-1_1920_1080_3840_1080/0/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk2-Noise.pm+Desk1-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png

eric        3069  0.3  0.0  62308 11216 tty1     S    12:18   0:00 fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/0/TILED_NULL+DVI-1_1920_1080_3840_1080/1/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk1-Noise.pm+Desk2-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png

eric        3070  0.3  0.0  62308 11248 tty1     S    12:18   0:00 fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/0/TILED_NULL+DVI-1_1920_1080_3840_1080/1/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk1-Noise.pm+Desk2-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png

eric        3077  0.5  0.0  62308  9112 tty1     S    12:18   0:00 fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/0/TILED_NULL+DVI-1_1920_1080_3840_1080/1/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk1-Noise.pm+Desk2-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png

eric        3078  1.0  0.0  62308  9096 tty1     S    12:18   0:00 fvwm-root -r /home/eric/.NsCDE/backer/bgcache/DVI-0_1920_1080_1920_1080/0/TILED_NULL+DVI-1_1920_1080_3840_1080/1/TILED_NULL+DVI-1-2_1920_1080_0_0/2/TILED_NULL+DVI-1-3_1920_1080_0_1080/3/TILED_NULL/Desk1-Noise.pm+Desk2-Noise.pm+Desk3-Noise.pm+Desk4-Noise.pm.png`

**Comment by no3m** [comment] 2022-02-20 18:22
playing around with 'feh', can apply unique backgrounds to all four monitors much quicker, eg.

$ time feh --no-fehbg --bg-scale '/home/eric/wallpaper/steelblue-grid20+100.png' /home/eric/wallpaper/steelblue-grid.png /home/eric/wallpaper/Selfoss-waterfall.jpg /home/eric/wallpaper/grey-grid20.png

real	0m0.325s
user 0m0.161s
sys	0m0.063s

Perhaps generating and caching the background PNGs for each desktop when background is selected/changed via the Style Manager - Backdrop... then use 'feh' to set the individual backgrounds in order instead of using fvwm-root and splicing together the individual background images into one large image to be applied to the root window?  The order of monitors that  feh apparently applies background to from this command 'xrandr --listactivemonitors'

**Comment by no3m** [comment] 2022-02-20 19:29
Looks like even just doing a single workspace switch (fvwm3 desktop model is shared) is invoking up to 5, maybe 6, fvwm-root processes when it should only be spawning one?  'convert' is not always called, but when it is, likely the same situation, multiple processes when one should be sufficient to splice the background images into one image to apply to the root.

**Comment by NsCDE** [comment] 2022-02-23 08:01
Using feh, nitrogen or any other setter instead for now hardcoded fvwm-root is in plan, but this does not solve what you are describing here. I was able to depend on fvwm-root which is part of FVWM anyway, but I will not like to depend on feh, so all other setters will be configurable instead of fvwm-root in ~/.NsCDE/NsCDE.conf.

ImageMagick convert is called only when there is no bgcache mapping between combinations of the two or in your case four workspaces. Next time, already generated background will be used, and you should see only one fvwm-root process.

I just tried with 4 virtual monitors in per-monitor mode and there is always one convert and one fvwm-root process. It is fast 1-2 seconds when there is need for convert (first use of workspaces combination), and almost immediate when there is only need for fvwm-root (bgcache exists). Two processors emulated only. Unless I use Meta+Tab pressed or pressing them really fast, then there is possibility to see couple of paralllel processes working, but never more than couple of seconds.

In shared mode. cache is pretty much fast generated for two monitor scenario, but for four monitors, there should be an option to pre-generate new cache in advance, and not on the first use. Any yes, using feh can help performance even when there is no need for convert in such extreme as four monitor in fvwm shared mode.

**Comment by NsCDE** [comment] 2022-02-23 15:37
I got now time to explore in depth behaviour of fvwm-root processes in shared mode in 4 monitor setup. It spawns 4 processes which are doing exactly the same thing! Setting the same png on the common background.

Now this _IS_ something to examine. In more often tested per-monitor mode, this is not a case.

**Comment by NsCDE** [comment] 2022-02-23 19:21
I have reported this bug to my "upstream" :-)
https://github.com/fvwmorg/fvwm3/issues/655

**Comment by 97-109-107** [comment] 2022-07-21 09:52
@no3m I've recently encountered a freeze when switching and manipulating _some_ windows. Can you confirm if the crash you encountered ever froze the whole system indefintely?

**Comment by NsCDE** [comment] 2022-10-01 17:40
Fixed in upstream.
https://github.com/fvwmorg/fvwm3/issues/655

**Closed by NsCDE** 2022-10-01 17:40 UTC
