### ISSUE TITLE
Workspace switcher

### ISSUE THREAD

**Issue by pavroo** [NsCDE/NsCDE#17] opened 2020-07-02 20:01 UTC
Hi
I have build and installed the latest rc21 on Debian stable & testing i686, amd64 and armhf.
The workspace switcher shows up on amd64 desktops only, but doesn't do that on i686 and armhf.
Any clue, please?
Regards
pavroo

**Comment by NsCDE** [comment] 2020-07-04 19:51
Hi,

Workspace Manager in the middle of Front Panel is FvwmScript application. Maybe the problem is in FvwmScript interpreter. This was the case on FreeBSD when FVWM was compiled with clang, but not with gcc.

Please see ~/.xsession-errors after starting NsCDE and also "dmesg | grep -i segfault" on affected platforms, so we can get closer to the cause of this issue.

**Comment by pavroo** [comment] 2020-07-06 20:03
The xsession-errors shows on i686 such errors:
`ERR: trouble loading pixmap
*** stack smashing detected ***: <unknown> terminated
xrandr: Failed to get size of gamma for output default
xrandr: Failed to get size of gamma for output default
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined`

dmesg shows nothing

**Comment by NsCDE** [comment] 2020-07-06 21:05
Lot of some warnings, but none of this looks like something about wha WSM is not started and swallowed in the Front Panel. Maybe some stack protector (there was such issue on FreeBSD in the past when FVWM was compiled with clang), but we must yet to confirm this.

Can you please edit temporary line 126 of /opt/NsCDE/bin/nscde and replace this:
`exec $FVWM_BIN -f ${NSCDE_ROOT}/config/NsCDE-Main.conf $FVWM_OPTS`
with
`exec $FVWM_BIN -f ${NSCDE_ROOT}/config/NsCDE-Main.conf $FVWM_OPTS >> /tmp/debugfile 2>&1`
logout and log in again. Send the contents of the /tmp/debugfile.

Do it please on i686 and armhf. Maybe it is the same cause, maybe not.

**Comment by pavroo** [comment] 2020-07-07 12:30
Enclosed zipped debug from i686 and armhf machines (doesn't support plain text files).
As addition, the clock couldn't been compiled during installation on armhf.

[debug1.zip](https://github.com/NsCDE/NsCDE/files/4884826/debug1.zip)

**Comment by NsCDE** [comment] 2020-07-08 13:58
Ok, now I'm pretty much sure this is about FvwmScript beeing compiled with -fstack-protector or some variation of this option like 
maybe -fstack-protector-all  -fstack-protector-strong -fstack-protector-explicit

This: *** stack smashing detected *** happens when WSM needs to be started.

You can try to recompile fvwm without any stack protector options (FvwmScript doesn't do networking anyway!) and if WSM works after that, you can ask on https://github.com/fvwmorg for FVWM authors to see if this is their bug to fix, or too much agressive gcc options for a valid non-networked code. Compile with CFLAGS="-O0 -g" so when this happens you can attache gdb on fvwm and send valuable output to developers of FVWM.

**Comment by pavroo** [comment] 2020-07-09 08:21
Will try to recompile fvwm.
Thanks for your help.

**Comment by NsCDE** [comment] 2020-08-28 14:05
Hi, do you have some findings about compiler flags impact on FVWM? This may be interesting since this was not the first time WSM FvwmScript failed to work with it's engine under such strict stack hardening. This is also interesting to report to my "upstream" that is, FVWM.

**Comment by NsCDE** [comment] 2020-09-03 14:06
Closing this for now.

**Comment by rtomsick** [comment] 2020-11-22 04:56
Just hit this on Fedora 33 on aarch64 (64-bit ARM), with rev 812734828.  

Built and installed fine, center spot of the panel (where we expect the "One", "Two", "Three", and "Four" buttons) is blank.  

`.xsession-errors` is blank.

**Comment by NsCDE** [comment] 2020-11-22 16:02
Hi,

1. I have heard of this missing workspace manager in the Front Panel problem here and there some time ago. It was never clear and never traced to the problem origin. I didn't tested it yet on F33. Please see what exact version of the fvwm you are using and if there are some core dumps (ulimit -c 0) from FvwmScript in which WSM is written (journalctl probably).

2. If .xsession-errors is blank, you will probably find display manager logs in journald log. See yournalctl -f. For "Watch Errors" to work with journalctl, see "InfoStoreAdd xlogcmd "journalctl -u gdm -n 300 -f"" example in the $NDCDE_ROOT/config/NsCDE.conf.

**Comment by NsCDE** [comment] 2020-11-27 22:17
FYI, you probably noticed it sometimes appears, sometimes not when you restart FVWM or Front Panel.

FvwmScript is core dumping when swallowed by FvwmButtons on Fedora 33 and possibly some other systems.

As a workaround, you can change "ModuleSynchronous" to "Module" in /opt/NsCDE/config/NsCDE-FrontPanel.conf at line ~317. It will segfault and blink a few times and eventually stay in the Front Panel. I will see with upstream what to do here.

**Comment by NsCDE** [comment] 2020-12-01 18:34
Closed by using "While" instead of "For" in Workspace Manager button pressed state changing routine. Original bug belongs to FvwmScript and has been introduced to FVWM upstream.

**Closed by NsCDE** 2020-12-01 18:34 UTC
Labels: bug
