### ISSUE TITLE
Keybindings: Duplicate functionality of Menu to Multi_key - Result in issue with ISO_Level3_Shift in xmodmap

### ISSUE THREAD

**Issue by drscream** [NsCDE/NsCDE#27] opened 2020-08-24 13:58 UTC
With the following commit https://github.com/NsCDE/NsCDE/commit/d3c53c1931e8f40aeb24676535546fac28cdd0c6 you added duplicate functionality of Menu to Multi_key. For example on my Thinkpad I use ISO_Level3_Shift (AltGr / Right Alt) to have some special functionality for Umlauts:

```
! Provide Umlaut support with altGr+u, altGr+o, altGr+a or with altGr+shift
keycode  26 = e E EuroSign cent EuroSign cent
keycode  30 = u U udiaeresis Udiaeresis udiaeresis Udiaeresis
keycode  32 = o O odiaeresis Odiaeresis odiaeresis Odiaeresis
keycode  38 = a A adiaeresis Adiaeresis adiaeresis Adiaeresis
keycode  39 = s S ssharp ssharp ssharp
```

With your commit this functionality isn't working anymore. I would like to ask for help if you might have any idea why or any idea about a workaround to support `xmodmap`.

**Comment by NsCDE** [comment] 2020-08-24 15:56
Hi drscream,

What a mess with this keycodes!

I have a new HP notebook which comes without Menu key on builting keyboard, which is normally present right of the space, alt and meta. That said, Menu key didn't worked anymore even with external keyboards (normal and Sun type 6 tried). According to xev(1) this key was recognised as "Multi_key" so I have naively de-facto aliased Multi_key to Menu key in config/NsCDE-Keybindings.conf. Now when I try it, it is not recognized as Multi_key anymore. Strange.

What is more interesting, I don't know what AltGr/AltGraph/ISO_Level3_Shift has anything with this. It was not affected on my layout with this change. I'm also using ISO_Level3_Shift heavily with my domestic keyboard layout, but AltGr or ISO_Level3_Shift is not the same as MultiKey on my layout.

So we have here at least 3 enigmas / unknowns.

For now, I will revert that change (remove Multi_key from keybindings), but I will like to examine this and try to understand.

Can you please open xev window (xev -event keyboard) put focus on it, and type your AltGr, Menu, and Meta keys and send it here.

In the meantime, fetch new commit on pending_release to revert ...

**Comment by drscream** [comment] 2020-08-24 18:57
Lovely keyboard layouts and keycodes ;-)

My Thinkpad do no provide a "Menu" key, they layout looks more like:

```
Fn Ctrl Win Alt Space AltGr PrtSc Ctrl
```

AltGr alias ISO_Level3_Shift:

```
KeyPress event, serial 25, synthetic NO, window 0x2000001,
    root 0x1d4, subw 0x2000002, time 26549332, (27,61), root:(78,184),
    state 0x0, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x2000001,
    root 0x1d4, subw 0x2000002, time 26549475, (27,61), root:(78,184),
    state 0x80, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Win alias Meta alias Super_L:

```
KeyPress event, serial 28, synthetic NO, window 0x2000001,
    root 0x1d4, subw 0x0, time 26583930, (117,108), root:(168,231),
    state 0x0, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x2000001,
    root 0x1d4, subw 0x0, time 26584040, (117,108), root:(168,231),
    state 0x40, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

PrtSc alias Print (which is at the location where Menu could be:

```
KeyPress event, serial 28, synthetic NO, window 0x2000001,
    root 0x1d4, subw 0x2000002, time 26610181, (46,28), root:(97,151),
    state 0x0, keycode 107 (keysym 0xff61, Print), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x2000001,
    root 0x1d4, subw 0x2000002, time 26610259, (46,28), root:(97,151),
    state 0x0, keycode 107 (keysym 0xff61, Print), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by NsCDE** [comment] 2020-08-26 23:27
No chance to find what was the cause which convinced me to de-facto alias Multi_key to Menu. This is not needed as I see now, and it also made your AltGr to fail. No issue anymore, closing this.

**Closed by NsCDE** 2020-08-26 23:27 UTC
